/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as DateIdRouteImport } from './routes/date.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProfileRoute,
} as any)
const DateIdRoute = DateIdRouteImport.update({
  id: '/date/$id',
  path: '/date/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/chat/$id': typeof ChatIdRoute
  '/date/$id': typeof DateIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/edit': typeof ProfileEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/chat/$id': typeof ChatIdRoute
  '/date/$id': typeof DateIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/edit': typeof ProfileEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/chat/$id': typeof ChatIdRoute
  '/date/$id': typeof DateIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/edit': typeof ProfileEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/inbox'
    | '/login'
    | '/matches'
    | '/onboarding'
    | '/profile'
    | '/safety'
    | '/signup'
    | '/chat/$id'
    | '/date/$id'
    | '/profile/$id'
    | '/profile/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/inbox'
    | '/login'
    | '/matches'
    | '/onboarding'
    | '/profile'
    | '/safety'
    | '/signup'
    | '/chat/$id'
    | '/date/$id'
    | '/profile/$id'
    | '/profile/edit'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/inbox'
    | '/login'
    | '/matches'
    | '/onboarding'
    | '/profile'
    | '/safety'
    | '/signup'
    | '/chat/$id'
    | '/date/$id'
    | '/profile/$id'
    | '/profile/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SafetyRoute: typeof SafetyRoute
  SignupRoute: typeof SignupRoute
  ChatIdRoute: typeof ChatIdRoute
  DateIdRoute: typeof DateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/date/$id': {
      id: '/date/$id'
      path: '/date/$id'
      fullPath: '/date/$id'
      preLoaderRoute: typeof DateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileIdRoute: typeof ProfileIdRoute
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileIdRoute: ProfileIdRoute,
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SafetyRoute: SafetyRoute,
  SignupRoute: SignupRoute,
  ChatIdRoute: ChatIdRoute,
  DateIdRoute: DateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
